import os
import pandas as pd
import csv

# Load the YAML into the config dictionary
configfile: "config.yml"

# Always relative to where the Snakefile lives
BASEDIR = workflow.basedir
ENV_DIR = os.path.join(BASEDIR, config["env_dir"])

# Definition of variables from config
input_dir = config['input_dir']
fastp_dir = config['fastp_dir']
env_dir = config['env_dir']
dada2_dir = config['dada2_dir']
results = config['results']

sample_table = pd.read_csv(config["sample_table"], sep="\t", comment="#")

SAMPLES = sample_table["sample"].tolist()

# Function to generate input file paths based on sample ID
def get_input_files(wc):
    row = sample_table[sample_table["sample"] == wc.sample].iloc[0]
    return {"read_1": row["R1"], "read_2": row["R2"]}


# Generate list of expected outputs
expected_outputs = (
    expand(f"{fastp_dir}/{{sample}}_1.clean.fastq.gz", sample=SAMPLES) +
    expand(f"{fastp_dir}/{{sample}}_2.clean.fastq.gz", sample=SAMPLES) +
    expand(f"{dada2_dir}/{{sample}}_filt1.fastq.gz", sample=SAMPLES) +
    expand(f"{dada2_dir}/{{sample}}_filt2.fastq.gz", sample=SAMPLES) +
    [f"{dada2_dir}/errF.rds", f"{dada2_dir}/errR.rds"] +
    expand(f"{dada2_dir}/{{sample}}_dadaFs.rds", sample=SAMPLES) +
    expand(f"{dada2_dir}/{{sample}}_dadaRs.rds", sample=SAMPLES) +
    expand(f"{dada2_dir}/{{sample}}_mergers.rds", sample=SAMPLES) +
    [f"{dada2_dir}/seqtab_nochim.rds"] +
    [f"{dada2_dir}/seqtab.rds"] +
    [f"{dada2_dir}/taxa.rds"] + 
    [f"{results}/taxonomy_counts_P.tsv", f"{results}/taxonomy_counts_G.tsv"] +
    [f"{results}/visuals/microbial_composition_overview_G.pdf"]
)

print(f"fastp conda env: {env_dir}/fastp_env.yml")

#workdir:
#    output_dir

include: "rules/fastp.rule"
include: "rules/dada2.rule"
include: "rules/diversity_analysis.rule"

rule all:
     input:
        expected_outputs
